apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
      - name: identity
        image: registry.azurecr.io/play.identity:1.0.0
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICE_BUS
          - name: ServiceSettings__KeyVaultName
            value: playeconomyzkv
          - name: IdentitySettings__PathBase
            value: /identity
          - name: IdentitySettings__CertificateCrtFilePath
            value: /certificates/certificate.crt
          - name: IdentitySettings__CertificateKeyFilePath
            value: /certificates/certificate.key
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5211
        livenessProbe:
          httpGet: 
            port: 5211
            path: /health/live
          initialDelaySeconds: 10
        readinessProbe:
          httpGet: 
            port: 5211
            path: /health/ready
          initialDelaySeconds: 10
        volumeMounts: 
          - name: certificate-volume
            mountPath: /certificates
      volumes:
        - name: certificate-volume
          secret: 
            secretName: signing-cert
            items: 
              - key: tls.key
                path: certificate.key
              - key: tls.crt
                path: certificate.crt
--- 
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5211
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount #match federated credentials of the labels in managed identity (identity)
  annotations:
    azure.workload.identity/client-id: #id of managed identity in azure key vault IAM
  labels:
    azure.workload.identity/use: "true"