apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: registry.azurecr.io/play.identity:1.0.0
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICE_BUS

        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5211
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5211
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount #match federated credentials of the labels in managed identity (identity)
  annotations:
    azure.workload.identity/client-id: #id of managed identity in azure key vault IAM
  labels:
    azure.workload.identity/use: "true"