apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: playeconomyregistry.azurecr.io/play.identity:1.0.0
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICE_BUS
          - name: ServiceBusSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: servicebus-connectionstring
          - name: MongoDbSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: mongo-connectionstring
          - name: IdentitySettings__AdminUserPassword
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: admin-password
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5211
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5211