services:
  db:
    image: mongo:4.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped  
  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
